# Generated by Django 2.2.13 on 2021-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "de_question",
                    models.CharField(
                        max_length=200, verbose_name="Faq-question in german"
                    ),
                ),
                (
                    "de_answer",
                    models.TextField(
                        max_length=500, verbose_name="Faq-answer in german"
                    ),
                ),
                (
                    "en_question",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Faq-question in english",
                    ),
                ),
                (
                    "en_answer",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Faq-answer in english",
                    ),
                ),
            ],
        )
    ]
