# Generated by Django 4.1.13 on 2023-11-23 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_faq_prioritization"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqHeading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "de_heading",
                    models.CharField(max_length=250, verbose_name="Faq-heading german"),
                ),
                (
                    "en_heading",
                    models.CharField(
                        max_length=250, verbose_name="Faq-heading english"
                    ),
                ),
                (
                    "prio_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Prio Heading (1 - 10)",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="faq",
            name="de_answer",
            field=models.TextField(max_length=500, verbose_name="Faq-answer german"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="de_question",
            field=models.CharField(max_length=200, verbose_name="Faq-question german"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="en_answer",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Faq-answer english"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="en_question",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Faq-question english",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="prioritization",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Prio (0 - 100)",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="faq_heading",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faq_heading",
                to="faq.faqheading",
            ),
        ),
    ]
