# Generated by Django 2.2.28 on 2023-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20230330_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='de_text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='de_title',
        ),
        migrations.AddField(
            model_name='message',
            name='en_text',
            field=models.TextField(blank=True, default='', verbose_name='text (Markdown)'),
        ),
        migrations.AddField(
            model_name='message',
            name='en_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
