version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false


formats:
  - pdf
  - epub