version: '3'

services:
  db:
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    restart: always
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.web
    command: /start.sh
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - RABBITMQ_URL=amqp://broker_adm:broker_pass@rabbit_broker:5672/
      - DJANGO_SECRET_KEY=h18i_1j3^d1e6iq8xur&yvbkpk08il9x^&9cf2l2%-0yqx7ss)
    volumes:
      - .:/app
    links:
      - rabbit_broker
      - celery_worker
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"

  rabbit_broker:
    hostname: "rabbit_broker"
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=broker_adm
      - RABBITMQ_DEFAULT_PASS=broker_pass
    ports:
      - "5673:5672"

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.celery
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_URL=amqp://broker_adm:broker_pass@rabbit_broker:5672/
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=h18i_1j3^d1e6iq8xur&yvbkpk08il9x^&9cf2l2%-0yqx7ss)
    volumes:
      - .:/app
    links:
      - rabbit_broker
      - db
    depends_on:
      - rabbit_broker
      - db
