# Generated by Django 2.2 on 2020-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_user_language")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")], max_length=2
            ),
        )
    ]
