# Generated by Django 2.2 on 2020-05-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0009_auto_20200427_2114")]

    operations = [
        migrations.AlterModelOptions(
            name="report", options={"ordering": ["month_year"]}
        )
    ]
