# Generated by Django 2.2.13 on 2020-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0010_report_ordering_month_year")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="personal_number",
            field=models.CharField(default="", max_length=100),
        ),
    ]
