# Generated by Django 2.2.13 on 2020-06-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0011_user_add_default_values")]

    operations = [
        migrations.RenameField(
            model_name="contract", old_name="hours", new_name="minutes"
        ),
        migrations.RenameField(
            model_name="report", old_name="hours", new_name="worktime"
        ),
    ]
