# Generated by Django 2.2.13 on 2020-06-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0013_auto_20200629_1902")]

    operations = [
        migrations.RenameField(
            model_name="report", old_name="minutes", new_name="worktime"
        )
    ]
