# Generated by Django 2.2.13 on 2020-07-11 19:09

from datetime import timedelta

from django.db import migrations, models


def populate_month_start_clocking(apps, schema_editor):
    Contract = apps.get_model("api", "Contract")
    for contract in Contract.objects.filter(carryover_target_date__isnull=True):
        contract.carryover_target_date = contract.start_date
        contract.save()


def revert_populate_month_start_clocking(apps, schema_editor):
    pass


def populate_start_carry_over(apps, schema_editor):
    Contract = apps.get_model("api", "Contract")
    for contract in Contract.objects.filter(initial_carryover__isnull=True):
        contract.initial_carryover = timedelta(0)
        contract.save()


def revert_populate_start_carry_over(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200702_1157'),
    ]
    state_operations = [
        migrations.AlterField(
            model_name='contract',
            name='carryover_target_date',
            field=models.DateField()
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_carryover',
            field=models.DurationField(),
        )
    ]
    database_operations = [
        migrations.RunPython(populate_month_start_clocking, reverse_code=revert_populate_month_start_clocking),
        migrations.RunPython(populate_start_carry_over, reverse_code=revert_populate_start_carry_over),
    ]
    operations = [
        migrations.AddField(
            model_name='contract',
            name='carryover_target_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='initial_carryover',
            field=models.DurationField(null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
    ]
