# Generated by Django 2.2.13 on 2020-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0016_auto_20200811_1639")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dsgvo_accepted",
            field=models.BooleanField(default=False),
        )
    ]
