# Generated by Django 2.2.18 on 2022-12-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_onboarding_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='carryover_target_date',
        ),
    ]
