# Generated by Django 2.2.28 on 2023-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230330_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
