# Generated by Django 2.2.28 on 2023-11-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_marked_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='color',
            field=models.CharField(default='#8ac5ff', max_length=7),
        ),
    ]
