# Generated by Django 4.1.11 on 2023-11-15 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_uuidtaggeditem_content_type_and_more"),
        ("api", "0023_user_marked_for_deletion"),
    ]

    operations = []
