# Generated by Django 4.1.13 on 2023-12-08 13:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_contract_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="vacation_time",
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
