# Generated by Django 4.1.13 on 2023-12-08 13:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_report_vacation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="vacation_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
