# Generated by Django 4.1.13 on 2023-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_report_vacation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="initial_vacation_carryover_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contract",
            name="initial_carryover_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
