# Generated by Django 4.1.13 on 2024-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_contract_worktime_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="worktime_model_name",
            field=models.CharField(
                choices=[
                    ("studEmp", "Studentische Hilfskraft"),
                    ("regEmp", "Regulär*er Angestelt*er"),
                    ("civilSer", "Beamt*in"),
                ],
                max_length=200,
                verbose_name="Validierungsklasse",
            ),
        ),
    ]
