# Generated by Django 4.1.13 on 2024-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_alter_contract_worktime_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="percent_fte",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Prozent einer Vollzeitstelle"
            ),
        ),
    ]
