# Generated by Django 4.2.9 on 2024-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_contract_percent_fte"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
