# Generated by Django 4.2.9 on 2024-05-17 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_user_is_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervised_references",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50, null=True),
                blank=True,
                default=[],
                size=None,
            ),
        ),
    ]
