# Generated by Django 4.2.9 on 2024-06-07 13:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_user_supervised_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="reference",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
