# Generated by Django 4.2.9 on 2025-10-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_contract_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="snack_time",
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name="user",
            name="timeout_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
