# Generated by Django 4.2.9 on 2025-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_contract_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.IntegerField(
                choices=[(0, "Student"), (1, "supervisor"), (2, "Clerk")], default=0
            ),
        ),
    ]
