# Generated by Django 4.2.9 on 2025-05-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_user_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.IntegerField(
                choices=[
                    (0, "Student"),
                    (1, "supervisor"),
                    (2, "Clerk"),
                    (3, "Approver"),
                ],
                default=0,
            ),
        ),
    ]
