# Generated by Django 4.2.9 on 2025-09-15 17:02

import api.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_remove_clockedinshift_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name="clockedinshift",
            old_name="created_by_user_id",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="clockedinshift",
            old_name="modified_by_user_id",
            new_name="modified_by",
        ),
        migrations.RenameField(
            model_name="clockedinshift",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="created_by_user_id",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="modified_by_user_id",
            new_name="modified_by",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="created_by_user_id",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="modified_by_user_id",
            new_name="modified_by",
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="user_id",
            new_name="user",
        ),
    ]
