# Generated by Django 4.2.9 on 2025-09-15 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="created_by_user_id",
            new_name="created_by",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="modified_by_user_id",
            new_name="modified_by",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="user_id",
            new_name="user",
        ),
    ]
