FROM python:3.6
ENV PYTHONBUFFERED=1
ADD ./api/ /app/
WORKDIR /app/

COPY Pipfile Pipfile.lock /
RUN pip install pipenv
RUN LIBRARY_PATH=/lib:/usr/lib /bin/sh -c "pipenv install --dev --system"
RUN useradd -ms /bin/bash celery-user
ENTRYPOINT celery worker -A project_celery.celery --concurrency=3 --loglevel=WARNING --uid=celery-user