FROM python:3.6
ADD ./api/ /app/
WORKDIR /app/
RUN useradd -ms /bin/bash celery-user
RUN pip install celery
ENTRYPOINT celery worker -A api.celery_inst --concurrency=20 --loglevel=WARNING --uid=celery-user