FROM python:3.7-slim
ENV PYTHONBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 POETRY_VERSION=1.2.0 POETRY_VIRTUALENVS_CREATE=false

RUN apt update \
	&& apt install -y gettext git

RUN curl -sSL https://install.python-poetry.org  | python3 -
COPY pyproject.toml poetry.lock /
RUN PATH="$PATH:$HOME/.local/bin" && poetry install

RUN useradd -ms /bin/bash celery-user

ADD ./api/ /app/
WORKDIR /app/
