name: pytest

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1

      - name: Install poetry dependencies
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.3.2 python3 -
          poetry install

      - name: Run unit tests
        run: docker-compose run --rm web pytest
