name: pytest

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Migrate new Changes
        run: docker-compose run --rm web python manage.py migrate

      - name: Build new Container
        run: docker-compose build

      - name: Run unit tests
        run: docker-compose run --rm web pytest
